[workspace]
authors = ["Andrew Matteson <andrew.matteson@certara.com>"]
channels = ["conda-forge"]
name = "certara-iq-vpop-training-1"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
abm = ">=2.1.6, <3"
import-ipynb = ">=0.2, <0.3"
ipykernel = ">=6.29.5, <7"
matplotlib = ">=3, <4"
nbconvert = ">=7.16.6, <8"
openpyxl = ">=3.1.5, <4"
plotnine = ">=0.14.5, <0.15"
tabulate = ">=0.9.0, <0.10"
